@startuml object

' オブジェクト図は
' ユーザーの要求に対するシステムの振る舞いを定義する図です。
' サンプルコードP18

rectangle {
    object "課題1" as TaskActivity1 {
        ID: "UUIDT1"
        生徒ID: "UUIDS1"
    }

    object "課題1のコンテンツ" as TaskContent1 {
        タイトル: "タイトル1"
        コンテンツ: "コンテンツ1"
    }

    object "課題1の状態" as TaskStatus1 {
        状態: "取り組み中"
    }

    TaskActivity1 *-- TaskContent1
    TaskActivity1 *-- TaskStatus1

    object "課題2" as TaskActivity2 {
        ID: "UUIDT2"
        生徒ID: "UUIDS1"
    }

    object "課題2のコンテンツ" as TaskContent2 {
        タイトル: "タイトル2"
        コンテンツ: "コンテンツ2"
    }

    object "課題2の状態" as TaskStatus2 {
        状態: "未着手"
    }

    TaskActivity2 *-- TaskContent2
    TaskActivity2 *-- TaskStatus2
}


object "生徒" as Student1 {
    生徒ID: "UUIDS1"
    名前: "花子 その１"
    メールアドレス: "hanako1@gmail.com"
    在籍状況: "在籍中"
}

TaskActivity1 --> Student1
TaskActivity2 --> Student1

@enduml

' https://tech.contracts.co.jp/entry/2020/10/16/150605